### ISSUE TITLE
RPi4 Are Unable to Boot

### ISSUE THREAD

**Issue by chr0n1x** [siderolabs/sbc-raspberrypi#48]
I made a comment here, but I'm unsure if it's relevant so figured I should make an issue here.

https://github.com/siderolabs/talos/issues/9981#issuecomment-2791315599

Image Factory config:

```yaml
overlay:
    image: siderolabs/sbc-raspberrypi
    name: rpi_generic
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
```

my exact steps

1. use rpi imager 1.8.5 to flash the eeprom onto the card
2. insert card into rpi 4, confirm green LED is infinitely flashing, HDMI screen is completely green
3. download the image from the factory, `xz -d metal-arm64.raw.xz`
4. take SD card, `dd of=/dev/{sdX} if=metal-amd64.raw conv=fsync bs=4M`
5. validate that multiple partitions written via `lsblk`, searing for my `/dev/{sdX}`
6. insert SD card into rpi4. fancy boot screen w/ a QR code + rpi logo pops up
7. immediately goes to rainbow [screen of death?] 😄 

any tips on how I can further debug?
